[General]

[UdpEndpoint Acc]
Address = 127.0.0.1
Port = 11100
Mode = Normal

[UdpEndpoint Free1]
Address = 127.0.0.1
Port = 22200
Mode = Normal

[UdpEndpoint Nmea]
Address = 127.0.0.1
Port = 33300
Mode = Normal

[UdpEndpoint Free2]
Address = 127.0.0.1
Port = 44400
Mode = Normal

[UdpEndpoint Tether]
Address = 0.0.0.0
Port = 14540
Mode = Server

[UartEndpoint Fc]
Device = /dev/ttyTHS1
Baud = 230400
